title: Karolis Pranciulis

email: pranciuliskarolis@gmail.com

github_username: karolispranciulis

include:
  - ".well-known"


collections:

  projects:
    output: true
    permalink: /projects/:name/

  plugins:
    output: true
    permalink: /plugins/:name/


defaults:

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  - scope:
      path: ""
      type: "plugins"
    values:
      layout: "project_ide"